/**
 * Prediction Ledger — sports picks: normalise the extracted pick, build the deterministic validation
 * plan, and cap the research budget (Release 1.2).
 *
 * Original concept: Michael D. Carter (BitsBeTrippin). Built with Claude AI assistance.
 * Licensed under the Apache License 2.0 — see LICENSE and NOTICE in the repository root.
 *
 * Product rule (owner, 2026-09-12): a prediction about a single game reduces to the WIN (moneyline),
 * the SPREAD, or the TOTAL, and validation is "did it happen after the game date" — no open-ended
 * research. So: the plan is generated by code (no model call, no criteria drift), the research budget
 * is a couple of score look-ups, and the assessment is a settlement rule rather than a judgement.
 */

import type { SportsPick } from "@prediction-ledger/shared";
import type { PlanOutput } from "./schemas.js";

export const SPORTS_RESEARCH_BUDGET = { searches: 3, sources: 3 } as const;

/** Extraction output → SportsPick, or undefined when the pick is not settleable as stated. */
export function normalizeSportsPick(raw: { sport: string; league?: string | null; teams: string[]; event_date?: string | null; pick_type: "moneyline" | "spread" | "total"; team?: string | null; line?: number | null; side?: "over" | "under" | null }): { pick?: SportsPick; problems: string[] } {
  const problems: string[] = [];
  const teams: [string, string] = [(raw.teams[0] ?? "").trim(), (raw.teams[1] ?? "").trim()];
  if (!teams[0] || !teams[1]) problems.push("Both teams must be named.");
  const eventDate = raw.event_date && /^\d{4}-\d{2}-\d{2}$/.test(raw.event_date) ? raw.event_date : undefined;
  if (raw.event_date && !eventDate) problems.push(`Game date "${raw.event_date}" is not a full date; deadline left unknown.`);
  const pick: SportsPick["pick"] = { type: raw.pick_type };
  if (raw.pick_type === "total") {
    if (typeof raw.line !== "number") problems.push("Total pick without a stated line cannot be settled.");
    if (!raw.side) problems.push("Total pick without over/under cannot be settled.");
    pick.line = raw.line ?? undefined;
    pick.side = raw.side ?? undefined;
  } else {
    const team = raw.team?.trim();
    const match = team ? teams.find((t) => sameTeam(t, team)) : undefined;
    if (!team) problems.push(`${raw.pick_type} pick names no team.`);
    else if (!match) problems.push(`Picked team "${team}" is not one of the two teams (${teams.join(" vs ")}).`);
    pick.team = match ?? team;
    if (raw.pick_type === "spread") {
      if (typeof raw.line !== "number") problems.push("Spread pick without a stated line cannot be settled.");
      pick.line = raw.line ?? undefined;
    }
  }
  return { pick: { sport: raw.sport.trim(), league: raw.league ?? undefined, teams, eventDate, pick }, problems };
}

function sameTeam(a: string, b: string): boolean {
  const na = a.toLowerCase().replace(/[^a-z0-9]/g, "");
  const nb = b.toLowerCase().replace(/[^a-z0-9]/g, "");
  return na === nb || na.endsWith(nb) || nb.endsWith(na) || na.includes(nb) || nb.includes(na);
}

/** One-line human summary, used for the normalized statement, the component, and the dashboard chip. */
export function describePick(p: SportsPick): string {
  const vs = `${p.teams[0]} vs ${p.teams[1]}`;
  const when = p.eventDate ? ` on ${p.eventDate}` : "";
  switch (p.pick.type) {
    case "moneyline":
      return `${p.pick.team} beat ${p.teams.find((t) => t !== p.pick.team) ?? "opponent"} (${p.sport}${when})`;
    case "spread":
      return `${p.pick.team} cover ${fmtLine(p.pick.line)} vs ${p.teams.find((t) => t !== p.pick.team) ?? "opponent"} (${p.sport}${when})`;
    case "total":
      return `${vs} total ${p.pick.side} ${p.pick.line ?? "?"} (${p.sport}${when})`;
  }
}

export function pickLabel(p: SportsPick): string {
  switch (p.pick.type) {
    case "moneyline": return `${p.sport} · ML ${p.pick.team}`;
    case "spread": return `${p.sport} · ${p.pick.team} ${fmtLine(p.pick.line)}`;
    case "total": return `${p.sport} · ${p.pick.side === "over" ? "O" : "U"} ${p.pick.line ?? "?"}`;
  }
}

function fmtLine(line?: number): string {
  if (line === undefined) return "(no line)";
  return line > 0 ? `+${line}` : String(line);
}

/**
 * Deterministic validation plan: the criteria are the settlement rules, the queries are score look-ups.
 * Same shape as a model-generated plan so research and assessment run unchanged.
 */
export function buildSportsPlan(p: SportsPick, dates: { predictionMade?: string; deadline?: string; researchCutoff: string }, componentStatement: string): PlanOutput {
  const [a, b] = p.teams;
  const date = p.eventDate ?? "";
  const other = p.teams.find((t) => t !== p.pick.team) ?? b;
  let supporting: string;
  let contradicting: string;
  let partial: string;
  switch (p.pick.type) {
    case "moneyline":
      supporting = `Final score shows ${p.pick.team} scored more than ${other} in this game.`;
      contradicting = `Final score shows ${other} scored more than ${p.pick.team}.`;
      partial = `The game ended in a draw/tie (a moneyline pick neither hits nor misses).`;
      break;
    case "spread":
      supporting = `Final margin for ${p.pick.team} minus ${other}, plus (${fmtLine(p.pick.line)}), is greater than 0 (favourite wins by more than the line; underdog wins outright or loses by less than the line).`;
      contradicting = `That adjusted margin is less than 0.`;
      partial = `That adjusted margin is exactly 0 (push).`;
      break;
    default:
      supporting = `Combined final score is ${p.pick.side === "over" ? "greater" : "less"} than ${p.pick.line}.`;
      contradicting = `Combined final score is ${p.pick.side === "over" ? "less" : "greater"} than ${p.pick.line}.`;
      partial = `Combined final score equals ${p.pick.line} exactly (push).`;
  }
  const q = (s: string) => s.replace(/\s+/g, " ").trim();
  const neutral = [q(`${a} vs ${b} final score ${date}`), q(`${a} ${b} box score ${date}`)];
  const supportingQ = [q(`${p.pick.team ?? a} ${p.pick.type === "total" ? "final score" : "win"} ${other} ${date}`)];
  const disconfirmingQ = [q(`${other} ${p.pick.type === "total" ? "final score" : "win"} ${p.pick.team ?? a} ${date}`), q(`${a} ${b} ${date} postponed OR cancelled`)];
  const proposition = componentStatement;
  return {
    proposition,
    components: [{ statement: componentStatement, kind: "future_claim", conditions: [] }],
    dates: { predictionMade: dates.predictionMade ?? null, deadline: dates.deadline ?? null, researchCutoff: dates.researchCutoff, notes: p.eventDate ? "Deadline is the game date; the pick settles at the final whistle." : "Game date not stated in the transcript — deadline unknown until the matchup is identified." },
    definitions: [
      { term: "final score", workingDefinition: "The official final result including overtime/extra time and shoot-outs as the league records them; not the score at regulation unless the pick said so." },
      ...(p.pick.type === "spread" ? [{ term: "cover", workingDefinition: `Final margin adjusted by the line ${fmtLine(p.pick.line)} is positive; exactly zero is a push.` }] : []),
      ...(p.pick.type === "total" ? [{ term: "total", workingDefinition: "Sum of both teams' final scores including overtime." }] : []),
    ],
    ambiguities: p.eventDate ? [] : ["Game date not stated; settle only if the matchup can be identified unambiguously."],
    supportingEvidence: [supporting],
    contradictingEvidence: [contradicting],
    partialFulfillmentCriteria: [partial],
    queries: { neutral, supporting: supportingQ, disconfirming: disconfirmingQ },
    preferredSourceTypes: ["league official site or app", "ESPN / AP / major outlet box score", "team official site"],
    outputSchemaNotes: "Sports pick: cite the evidence item carrying the final score; explanation is the score and how it settles the pick.",
    researchPrompt: `Find the official final score of ${a} vs ${b}${date ? ` played on ${date}` : ""} (${p.sport}${p.league ? `, ${p.league}` : ""}). Record both teams' final points and whether the game went to overtime. Do not use previews, odds, or predictions as evidence. If the game was postponed, cancelled, or has not been played, say so instead of guessing. The pick to settle: ${describePick(p)}.`,
  };
}
