/**
 * Prediction Ledger — sports picks: normalise the extracted pick, build the deterministic validation
 * plan, and cap the research budget (Release 1.2).
 *
 * Original concept: Michael D. Carter (BitsBeTrippin). Built with Claude AI assistance.
 * Licensed under the Apache License 2.0 — see LICENSE and NOTICE in the repository root.
 *
 * Product rule (owner, 2026-09-12): a prediction about a single game reduces to the WIN (moneyline),
 * the SPREAD, or the TOTAL, and validation is "did it happen after the game date" — no open-ended
 * research. So: the plan is generated by code (no model call, no criteria drift), the research budget
 * is a couple of score look-ups, and the assessment is a settlement rule rather than a judgement.
 */

import type { SportsPick } from "@prediction-ledger/shared";
import type { PlanOutput } from "./schemas.js";

export const SPORTS_RESEARCH_BUDGET = { searches: 3, sources: 3 } as const;

/**
 * Trusted final-score sources. "Validate scores" prefers results from these hosts and, when any are
 * present, fetches only those — a box score from a league or major outlet is enough to settle a pick.
 */
export const TRUSTED_SCORE_HOSTS = [
  "espn.com", "nfl.com", "nba.com", "nhl.com", "mlb.com", "ncaa.com", "mlssoccer.com", "premierleague.com", "uefa.com", "fifa.com",
  "cbssports.com", "foxsports.com", "sports.yahoo.com", "nbcsports.com", "apnews.com", "reuters.com", "bbc.co.uk", "bbc.com", "skysports.com",
  "theathletic.com", "si.com", "pro-football-reference.com", "basketball-reference.com", "hockey-reference.com", "baseball-reference.com", "fbref.com", "flashscore.com", "sofascore.com",
];

export function isTrustedScoreHost(url: string): boolean {
  try {
    const host = new URL(url).hostname.toLowerCase();
    return TRUSTED_SCORE_HOSTS.some((h) => host === h || host.endsWith("." + h));
  } catch {
    return false;
  }
}

/** Extraction output → SportsPick, or undefined when the pick is not settleable as stated. */
export function normalizeSportsPick(raw: { sport: string; league?: string | null; teams: string[]; event_date?: string | null; event_time?: string | null; event_hint?: string | null; pick_type: "moneyline" | "spread" | "total"; team?: string | null; line?: number | null; side?: "over" | "under" | null }, opts: { trackSpreads?: boolean } = {}): { pick?: SportsPick; problems: string[] } {
  const problems: string[] = [];
  if (raw.pick_type === "spread" && opts.trackSpreads === false) {
    // Setup → Sports Mode → "Track point spreads" off: the pick is recorded as win/loss on the named team.
    problems.push(`Spread ${raw.line ?? ""} ignored (Setup → Sports Mode → track point spreads is off); recorded as a win/loss pick.`);
    raw = { ...raw, pick_type: "moneyline", line: null };
  }
  const teams: [string, string] = [(raw.teams[0] ?? "").trim(), (raw.teams[1] ?? "").trim()];
  if (!teams[0] || !teams[1]) problems.push("Both teams must be named.");
  const eventDate = raw.event_date && /^\d{4}-\d{2}-\d{2}$/.test(raw.event_date) ? raw.event_date : undefined;
  if (raw.event_date && !eventDate) problems.push(`Game date "${raw.event_date}" is not a full date; deadline left unknown.`);
  const pick: SportsPick["pick"] = { type: raw.pick_type };
  if (raw.pick_type === "total") {
    if (typeof raw.line !== "number") problems.push("Total pick without a stated line cannot be settled.");
    if (!raw.side) problems.push("Total pick without over/under cannot be settled.");
    pick.line = raw.line ?? undefined;
    pick.side = raw.side ?? undefined;
  } else {
    const team = raw.team?.trim();
    const match = team ? teams.find((t) => sameTeam(t, team)) : undefined;
    if (!team) problems.push(`${raw.pick_type} pick names no team.`);
    else if (!match) problems.push(`Picked team "${team}" is not one of the two teams (${teams.join(" vs ")}).`);
    pick.team = match ?? team;
    if (raw.pick_type === "spread") {
      if (typeof raw.line !== "number") problems.push("Spread pick without a stated line cannot be settled.");
      pick.line = raw.line ?? undefined;
    }
  }
  return {
    pick: { sport: raw.sport.trim(), league: raw.league ?? undefined, teams, eventDate, eventTime: raw.event_time?.trim() || undefined, eventHint: raw.event_hint?.trim() || undefined, eventDateSource: eventDate ? "transcript" : undefined, pick },
    problems,
  };
}

/** Loose team-name equality: "Chiefs" ~ "Kansas City Chiefs" ~ "KC Chiefs". */
export function sameTeamName(a: string, b: string): boolean {
  return sameTeam(a, b);
}

function sameTeam(a: string, b: string): boolean {
  const na = a.toLowerCase().replace(/[^a-z0-9]/g, "");
  const nb = b.toLowerCase().replace(/[^a-z0-9]/g, "");
  return na === nb || na.endsWith(nb) || nb.endsWith(na) || na.includes(nb) || nb.includes(na);
}

/** One-line human summary, used for the normalized statement, the component, and the dashboard chip. */
export function describePick(p: SportsPick): string {
  const vs = `${p.teams[0]} vs ${p.teams[1]}`;
  const when = p.eventDate ? ` on ${p.eventDate}` : "";
  switch (p.pick.type) {
    case "moneyline":
      return `${p.pick.team} beat ${p.teams.find((t) => t !== p.pick.team) ?? "opponent"} (${p.sport}${when})`;
    case "spread":
      return `${p.pick.team} cover ${fmtLine(p.pick.line)} vs ${p.teams.find((t) => t !== p.pick.team) ?? "opponent"} (${p.sport}${when})`;
    case "total":
      return `${vs} total ${p.pick.side} ${p.pick.line ?? "?"} (${p.sport}${when})`;
  }
}

export function pickLabel(p: SportsPick): string {
  switch (p.pick.type) {
    case "moneyline": return `${p.sport} · ML ${p.pick.team}`;
    case "spread": return `${p.sport} · ${p.pick.team} ${fmtLine(p.pick.line)}`;
    case "total": return `${p.sport} · ${p.pick.side === "over" ? "O" : "U"} ${p.pick.line ?? "?"}`;
  }
}

function fmtLine(line?: number): string {
  if (line === undefined) return "(no line)";
  return line > 0 ? `+${line}` : String(line);
}

/**
 * Deterministic validation plan: the criteria are the settlement rules, the queries are score look-ups.
 * Same shape as a model-generated plan so research and assessment run unchanged.
 */
export function buildSportsPlan(p: SportsPick, dates: { predictionMade?: string; deadline?: string; researchCutoff: string }, componentStatement: string): PlanOutput {
  const [a, b] = p.teams;
  const date = p.eventDate ?? "";
  const other = p.teams.find((t) => t !== p.pick.team) ?? b;
  let supporting: string;
  let contradicting: string;
  let partial: string;
  switch (p.pick.type) {
    case "moneyline":
      supporting = `Final score shows ${p.pick.team} scored more than ${other} in this game.`;
      contradicting = `Final score shows ${other} scored more than ${p.pick.team}.`;
      partial = `The game ended in a draw/tie (a moneyline pick neither hits nor misses).`;
      break;
    case "spread":
      supporting = `Final margin for ${p.pick.team} minus ${other}, plus (${fmtLine(p.pick.line)}), is greater than 0 (favourite wins by more than the line; underdog wins outright or loses by less than the line).`;
      contradicting = `That adjusted margin is less than 0.`;
      partial = `That adjusted margin is exactly 0 (push).`;
      break;
    default:
      supporting = `Combined final score is ${p.pick.side === "over" ? "greater" : "less"} than ${p.pick.line}.`;
      contradicting = `Combined final score is ${p.pick.side === "over" ? "less" : "greater"} than ${p.pick.line}.`;
      partial = `Combined final score equals ${p.pick.line} exactly (push).`;
  }
  const q = (s: string) => s.replace(/\s+/g, " ").trim();
  const neutral = [q(`${a} vs ${b} final score ${date}`), q(`${a} ${b} box score ${date}`)];
  const supportingQ = [q(`${p.pick.team ?? a} ${p.pick.type === "total" ? "final score" : "win"} ${other} ${date}`)];
  const disconfirmingQ = [q(`${other} ${p.pick.type === "total" ? "final score" : "win"} ${p.pick.team ?? a} ${date}`), q(`${a} ${b} ${date} postponed OR cancelled`)];
  const proposition = componentStatement;
  return {
    proposition,
    components: [{ statement: componentStatement, kind: "future_claim", conditions: [] }],
    dates: { predictionMade: dates.predictionMade ?? null, deadline: dates.deadline ?? null, researchCutoff: dates.researchCutoff, notes: p.eventDate ? "Deadline is the game date; the pick settles at the final whistle." : "Game date not stated in the transcript — deadline unknown until the matchup is identified." },
    definitions: [
      { term: "final score", workingDefinition: "The official final result including overtime/extra time and shoot-outs as the league records them; not the score at regulation unless the pick said so." },
      ...(p.pick.type === "spread" ? [{ term: "cover", workingDefinition: `Final margin adjusted by the line ${fmtLine(p.pick.line)} is positive; exactly zero is a push.` }] : []),
      ...(p.pick.type === "total" ? [{ term: "total", workingDefinition: "Sum of both teams' final scores including overtime." }] : []),
    ],
    ambiguities: p.eventDate ? [] : ["Game date not stated; settle only if the matchup can be identified unambiguously."],
    supportingEvidence: [supporting],
    contradictingEvidence: [contradicting],
    partialFulfillmentCriteria: [partial],
    queries: { neutral, supporting: supportingQ, disconfirming: disconfirmingQ },
    preferredSourceTypes: ["league official site or app", "ESPN / AP / major outlet box score", "team official site"],
    outputSchemaNotes: "Sports pick: cite the evidence item carrying the final score; explanation is the score and how it settles the pick.",
    researchPrompt: `Find the official final score of ${a} vs ${b}${date ? ` played on ${date}` : ""} (${p.sport}${p.league ? `, ${p.league}` : ""}). Record both teams' final points and whether the game went to overtime. Do not use previews, odds, or predictions as evidence. If the game was postponed, cancelled, or has not been played, say so instead of guessing. The pick to settle: ${describePick(p)}.`,
  };
}

// ---------------------------------------------------------------------------
// 1.3.1 — schedule look-up: find the game date/time when the transcript never says it.
// ---------------------------------------------------------------------------

export const SCHEDULE_LOOKUP_BUDGET = { searches: 2, sources: 3 } as const;

/** Search queries for the schedule page. `anchor` (video publication date) supplies the season/year. */
export function buildScheduleQueries(p: SportsPick, anchor?: string): string[] {
  const [a, b] = p.teams;
  const year = anchor && /^\d{4}/.test(anchor) ? anchor.slice(0, 4) : new Date().toISOString().slice(0, 4);
  const league = p.league ?? p.sport;
  const hint = p.eventHint ?? "";
  const q = (s: string) => s.replace(/\s+/g, " ").trim();
  return [q(`${a} vs ${b} ${league} ${hint} ${year} game date time`), q(`${league} ${year} schedule ${a} ${b}`)];
}

export interface GameDateCandidate {
  eventDate: string;
  eventTime?: string;
  /** How many date mentions in the text sat next to both team names. */
  hits: number;
}

export interface GameDateHit extends GameDateCandidate {
  /** Another in-window date scored as many hits — do not trust without confirmation. */
  ambiguous: boolean;
}

const MONTHS: Record<string, number> = { jan: 1, feb: 2, mar: 3, apr: 4, may: 5, jun: 6, jul: 7, aug: 8, sep: 9, sept: 9, oct: 10, nov: 11, dec: 12 };
const MONTH_RE = "(jan(?:uary)?|feb(?:ruary)?|mar(?:ch)?|apr(?:il)?|may|jun(?:e)?|jul(?:y)?|aug(?:ust)?|sep(?:t(?:ember)?)?|oct(?:ober)?|nov(?:ember)?|dec(?:ember)?)";
const DATE_RE = new RegExp(
  `\\b${MONTH_RE}\\.?\\s+(\\d{1,2})(?:st|nd|rd|th)?(?:,?\\s+(\\d{4}))?\\b` + // September 9, 2026 / Sept. 9
    `|\\b(\\d{1,2})\\s+${MONTH_RE}\\.?(?:,?\\s+(\\d{4}))?\\b` + // 9 September 2026
    `|\\b(\\d{1,2})/(\\d{1,2})(?:/(\\d{2,4}))?\\b` + // 9/9/2026 (US month/day)
    `|\\b(\\d{4})-(\\d{2})-(\\d{2})\\b`, // ISO
  "gi",
);
const TIME_RE = /\b(\d{1,2})(?::(\d{2}))?\s*(a\.?m\.?|p\.?m\.?)\s*(ET|EST|EDT|CT|CST|CDT|MT|MST|MDT|PT|PST|PDT|GMT|BST|UTC)?\b/i;

function pad(n: number): string {
  return String(n).padStart(2, "0");
}
function isoDate(y: number, m: number, d: number): string | undefined {
  if (m < 1 || m > 12 || d < 1 || d > 31) return undefined;
  const dt = new Date(Date.UTC(y, m - 1, d));
  if (dt.getUTCMonth() !== m - 1 || dt.getUTCDate() !== d) return undefined;
  return `${y}-${pad(m)}-${pad(d)}`;
}
function dayDiff(a: string, b: string): number {
  return Math.round((Date.parse(a + "T00:00:00Z") - Date.parse(b + "T00:00:00Z")) / 86_400_000);
}
/** Year-less dates take the year that lands them closest to the anchor. */
function withNearestYear(m: number, d: number, anchor: string): string | undefined {
  const y0 = Number(anchor.slice(0, 4));
  let best: string | undefined;
  for (const y of [y0 - 1, y0, y0 + 1]) {
    const iso = isoDate(y, m, d);
    if (!iso) continue;
    if (!best || Math.abs(dayDiff(iso, anchor)) < Math.abs(dayDiff(best, anchor))) best = iso;
  }
  return best;
}

/** True when the team is mentioned in the text: nickname (last word ≥ 3 chars) or the full name. */
export function teamMentioned(text: string, team: string): boolean {
  const t = text.toLowerCase();
  const words = team.toLowerCase().split(/\s+/).filter(Boolean);
  const nick = words[words.length - 1];
  if (nick && nick.length >= 3 && new RegExp(`\\b${nick.replace(/[^a-z0-9]/g, "")}\\b`, "i").test(t.replace(/[^a-z0-9\s]/g, " "))) return true;
  return t.includes(team.toLowerCase());
}

/**
 * Deterministic schedule parser. Every date mention whose surrounding text (its own line before it; up
 * to the next date mention after it) names BOTH teams is a candidate; candidates are kept only inside a plausible window around the anchor (video date):
 * 14 days before to 45 days after. The winner has the most hits; ties resolve to the date nearest the
 * anchor and are flagged ambiguous. A kick-off time in the same window is attached when present.
 */
export function findGameDate(text: string, p: SportsPick, opts: { anchor?: string; radius?: number } = {}): GameDateHit | undefined {
  const anchor = opts.anchor && /^\d{4}-\d{2}-\d{2}/.test(opts.anchor) ? opts.anchor.slice(0, 10) : new Date().toISOString().slice(0, 10);
  const radius = opts.radius ?? 300;
  const tally = new Map<string, GameDateCandidate>();
  DATE_RE.lastIndex = 0;
  const matches: RegExpExecArray[] = [];
  for (let m = DATE_RE.exec(text); m; m = DATE_RE.exec(text)) matches.push(m);
  for (let i = 0; i < matches.length; i++) {
    const m = matches[i];
    let iso: string | undefined;
    if (m[1]) iso = m[3] ? isoDate(Number(m[3]), MONTHS[m[1].toLowerCase().slice(0, 4)] ?? MONTHS[m[1].toLowerCase().slice(0, 3)], Number(m[2])) : withNearestYear(MONTHS[m[1].toLowerCase().slice(0, 4)] ?? MONTHS[m[1].toLowerCase().slice(0, 3)], Number(m[2]), anchor);
    else if (m[5]) iso = m[6] ? isoDate(Number(m[6]), MONTHS[m[5].toLowerCase().slice(0, 4)] ?? MONTHS[m[5].toLowerCase().slice(0, 3)], Number(m[4])) : withNearestYear(MONTHS[m[5].toLowerCase().slice(0, 4)] ?? MONTHS[m[5].toLowerCase().slice(0, 3)], Number(m[4]), anchor);
    else if (m[7]) iso = m[9] ? isoDate(m[9].length === 2 ? 2000 + Number(m[9]) : Number(m[9]), Number(m[7]), Number(m[8])) : withNearestYear(Number(m[7]), Number(m[8]), anchor);
    else if (m[10]) iso = isoDate(Number(m[10]), Number(m[11]), Number(m[12]));
    if (!iso) continue;
    const diff = dayDiff(iso, anchor);
    if (diff < -14 || diff > 45) continue;
    // A date "owns" the rest of its own line/paragraph and the following ones up to the next date
    // mention (date header + game rows), but only its own line before it — so adjacent schedule
    // rows ("Sept. 10 — A at B / Sept. 13 — C at D") never bleed into each other.
    const lineStart = text.lastIndexOf("\n", m.index) + 1;
    const prevEnd = i > 0 ? matches[i - 1].index + matches[i - 1][0].length : 0;
    const nextStart = i + 1 < matches.length ? matches[i + 1].index : text.length;
    const window = text.slice(Math.max(prevEnd, lineStart, m.index - radius), Math.min(nextStart, m.index + m[0].length + radius));
    if (!teamMentioned(window, p.teams[0]) || !teamMentioned(window, p.teams[1])) continue;
    const c = tally.get(iso) ?? { eventDate: iso, hits: 0 };
    c.hits++;
    if (!c.eventTime) {
      const t = TIME_RE.exec(window);
      if (t) c.eventTime = `${t[1]}${t[2] ? ":" + t[2] : ""} ${t[3].replace(/\./g, "").toUpperCase()}${t[4] ? " " + t[4].toUpperCase() : ""}`;
    }
    tally.set(iso, c);
  }
  const ranked = [...tally.values()].sort((x, y) => y.hits - x.hits || Math.abs(dayDiff(x.eventDate, anchor)) - Math.abs(dayDiff(y.eventDate, anchor)));
  if (ranked.length === 0) return undefined;
  const best = ranked[0];
  const ambiguous = ranked.length > 1 && ranked[1].hits === best.hits;
  return { ...best, ambiguous };
}

// ---------------------------------------------------------------------------
// 1.4 — game records: identify the matchup, read the final score, settle each pick by rule.
// ---------------------------------------------------------------------------

export const GAME_LOOKUP_BUDGET = { searches: 2, sources: 3 } as const;

/** Team nickname — the last word ("Kansas City Chiefs" → "chiefs"); the whole name for one-word teams. */
export function teamNick(team: string): string {
  const words = team.toLowerCase().replace(/[^a-z0-9\s]/g, " ").split(/\s+/).filter(Boolean);
  return words[words.length - 1] ?? team.toLowerCase();
}

/** Stable key shared by every pick on the same game: sport + both nicknames, sorted. */
export function matchupKey(p: Pick<SportsPick, "sport" | "teams">): string {
  return `${p.sport.toLowerCase().replace(/[^a-z0-9]/g, "")}:${[teamNick(p.teams[0]), teamNick(p.teams[1])].sort().join("|")}`;
}

/** Queries for the final score; the date (or the spoken hint + season) narrows them to one game. */
export function buildScoreQueries(p: SportsPick, anchor?: string): string[] {
  const [a, b] = p.teams;
  const year = anchor && /^\d{4}/.test(anchor) ? anchor.slice(0, 4) : new Date().toISOString().slice(0, 4);
  const when = p.eventDate ?? `${p.eventHint ?? ""} ${year}`;
  const q = (s: string) => s.replace(/\s+/g, " ").trim();
  return [q(`${a} vs ${b} final score ${when}`), q(`${a} ${b} ${p.league ?? p.sport} box score ${when}`)];
}

export interface FinalScoreHit {
  /** Scores in the pick's `teams` order. */
  scores: [number, number];
  weight: number;
  /** Verbatim line the score was read from (substring of the input text). */
  excerpt: string;
  overtime: boolean;
  ambiguous: boolean;
}

const NOISE_RE = /\b(predict|prediction|odds|preview|projected|projection|expected|moneyline|favou?rite|underdog|point spread|betting|parlay|prop bet|picks?\b|lines?\b)/i;
const POSTPONED_RE = /\b(postponed|cancell?ed|suspended|abandoned)\b/i;
const WIN_VERB_RE = /\b(beat|beats|defeat|defeats|defeated|def\.|top|tops|topped|over|down|downs|downed|rout|routs|routed|edge|edges|edged|upset|upsets|win|wins|won|held off|hold off|holds off|survive|survives|cruise past|blank|blanks|shut out)\b/i;

function teamRe(team: string): RegExp {
  const nick = teamNick(team).replace(/[^a-z0-9]/g, "");
  const full = team.toLowerCase().replace(/[^a-z0-9\s]/g, "").trim().replace(/\s+/g, "\\s+");
  return new RegExp(`\\b(?:${full}|${nick})\\b`, "i");
}

/**
 * Deterministic final-score reader. Works line by line (extracted pages and search snippets keep
 * their line structure): a line that names both teams and is not betting/preview chatter yields a
 * candidate from "Team 27, Team 20" (weight 2) or "27-20" next to a win verb / in mention order
 * (weight 1); "final" adds weight. The top candidate wins; a tie between different scores is
 * flagged ambiguous. Postponed/cancelled wording is reported separately so nothing is settled.
 */
export function findFinalScore(text: string, p: SportsPick): { hit?: FinalScoreHit; postponed?: string } {
  const [ta, tb] = p.teams;
  const reA = teamRe(ta);
  const reB = teamRe(tb);
  const tally = new Map<string, FinalScoreHit & { excerptWeight: number }>();
  let postponed: string | undefined;
  for (const raw of text.split(/\n+/)) {
    const line = raw.trim();
    if (line.length < 8 || !reA.test(line) || !reB.test(line)) continue;
    if (POSTPONED_RE.test(line) && !postponed) postponed = line.slice(0, 240);
    if (NOISE_RE.test(line)) continue;
    const bonus = /\bfinal\b/i.test(line) ? 1 : 0;
    const overtime = /\b(OT|overtime|extra time|shoot-?out|penalties)\b/i.test(line);
    const add = (scores: [number, number], weight: number) => {
      if (scores[0] > 250 || scores[1] > 250) return;
      const key = scores.join("-");
      const c = tally.get(key) ?? { scores, weight: 0, excerpt: line.slice(0, 240), overtime, ambiguous: false, excerptWeight: 0 };
      c.weight += weight + bonus;
      c.overtime = c.overtime || overtime;
      if (weight + bonus > c.excerptWeight) {
        c.excerpt = line.slice(0, 240); // quote the most explicit line ("Final: A 27, B 20"), not the first one
        c.excerptWeight = weight + bonus;
      }
      tally.set(key, c);
    };
    // "Chiefs 27, Bills 20" / "Kansas City Chiefs 27 – Buffalo Bills 20"
    const after = (re: RegExp): number | undefined => {
      // Only punctuation/space may sit between the name and its score, and "27" must not be a record ("2-0").
      const m = new RegExp(`${re.source}[\\s:,.\\-–—]{0,6}(\\d{1,3})(?![-–]\\d)\\b`, "i").exec(line);
      return m ? Number(m[1]) : undefined;
    };
    const sa = after(reA);
    const sb = after(reB);
    if (sa !== undefined && sb !== undefined) add([sa, sb], 2);
    else {
      // "Chiefs beat Bills 27-20" / "Bills fall to Chiefs, 20-27"
      const m = /(?<!\()\b(\d{1,3})\s*[-–—]\s*(\d{1,3})\b(?!\))/.exec(line);
      if (m) {
        const n1 = Number(m[1]);
        const n2 = Number(m[2]);
        const ia = line.search(reA);
        const ib = line.search(reB);
        const verb = WIN_VERB_RE.exec(line);
        let scores: [number, number];
        if (verb) {
          const winnerIsA = ia < verb.index && (ib > verb.index || ia < ib);
          scores = winnerIsA ? [Math.max(n1, n2), Math.min(n1, n2)] : [Math.min(n1, n2), Math.max(n1, n2)];
        } else scores = ia <= ib ? [n1, n2] : [n2, n1];
        add(scores, 1);
      }
    }
  }
  const ranked = [...tally.values()].sort((x, y) => y.weight - x.weight);
  if (ranked.length === 0) return { postponed };
  const { excerptWeight: _w, ...best } = ranked[0];
  best.ambiguous = ranked.length > 1 && ranked[1].weight === best.weight;
  return { hit: best, postponed };
}

export type SettleOutcome = "hit" | "miss" | "push" | "pending" | "void";

/**
 * Settlement by rule. `game.scores` are in `game.teams` order; the pick's teams are matched by name.
 * hit → supported, miss → contradicted, push/tie → partially supported; anything unplayed is pending.
 */
export function settlePick(p: SportsPick, game: { teams: [string, string]; scores?: [number, number]; status: string; eventDate?: string; overtime?: boolean }): { outcome: SettleOutcome; assessment?: "supported" | "contradicted" | "partially_supported" | "not_assessable"; explanation: string } {
  const when = game.eventDate ? ` on ${game.eventDate}` : "";
  if (game.status === "postponed") return { outcome: "pending", explanation: `${game.teams[0]} vs ${game.teams[1]} was postponed or cancelled; the pick stays open until the game is played.` };
  if (game.status !== "final" || !game.scores) return { outcome: "pending", explanation: `No final score is recorded for ${game.teams[0]} vs ${game.teams[1]}${when} yet.` };
  const scoreOf = (team: string): number | undefined => {
    const i = game.teams.findIndex((t) => sameTeam(t, team));
    return i >= 0 ? game.scores![i] : undefined;
  };
  const other = p.teams.find((t) => !sameTeam(t, p.pick.team ?? ""))!;
  const winner = game.scores[0] === game.scores[1] ? undefined : game.scores[0] > game.scores[1] ? game.teams[0] : game.teams[1];
  const loser = winner ? game.teams.find((t) => t !== winner)! : undefined;
  const ot = game.overtime ? " (OT)" : "";
  const scoreLine = winner ? `${winner} beat ${loser} ${Math.max(...game.scores)}–${Math.min(...game.scores)}${ot}${when}` : `${game.teams[0]} and ${game.teams[1]} tied ${game.scores[0]}–${game.scores[1]}${ot}${when}`;
  if (p.pick.type === "total") {
    if (p.pick.line === undefined || !p.pick.side) return { outcome: "void", assessment: "not_assessable", explanation: `${scoreLine}. The total pick has no usable line/side, so it cannot be settled.` };
    const sum = game.scores[0] + game.scores[1];
    const outcome: SettleOutcome = sum === p.pick.line ? "push" : (sum > p.pick.line) === (p.pick.side === "over") ? "hit" : "miss";
    return { outcome, assessment: toAssessment(outcome), explanation: `${scoreLine}: combined ${sum} vs the ${p.pick.side} ${p.pick.line} line → ${label(outcome)}.` };
  }
  const mine = scoreOf(p.pick.team ?? "");
  const theirs = scoreOf(other);
  if (mine === undefined || theirs === undefined) return { outcome: "void", assessment: "not_assessable", explanation: `${scoreLine}. Could not match "${p.pick.team}" / "${other}" to the game's teams.` };
  if (p.pick.type === "moneyline") {
    const outcome: SettleOutcome = mine === theirs ? "push" : mine > theirs ? "hit" : "miss";
    return { outcome, assessment: toAssessment(outcome), explanation: `${scoreLine}. Pick: ${p.pick.team} to win → ${label(outcome)}.` };
  }
  if (p.pick.line === undefined) return { outcome: "void", assessment: "not_assessable", explanation: `${scoreLine}. The spread pick has no line, so it cannot be settled.` };
  const adj = mine - theirs + p.pick.line;
  const outcome: SettleOutcome = adj === 0 ? "push" : adj > 0 ? "hit" : "miss";
  return { outcome, assessment: toAssessment(outcome), explanation: `${scoreLine}. Pick: ${p.pick.team} ${fmtLine(p.pick.line)} → margin ${mine - theirs >= 0 ? "+" : ""}${mine - theirs}, adjusted ${adj > 0 ? "+" : ""}${adj} → ${label(outcome)}.` };
}

function toAssessment(o: SettleOutcome): "supported" | "contradicted" | "partially_supported" {
  return o === "hit" ? "supported" : o === "miss" ? "contradicted" : "partially_supported";
}
function label(o: SettleOutcome): string {
  return o === "hit" ? "HIT" : o === "miss" ? "MISS" : o === "push" ? "PUSH" : o.toUpperCase();
}
