/**
 * Prediction Ledger — ffmpeg / ffprobe wrapper (probe, audio extraction, silence check, chunk cutting).
 *
 * Original concept: Michael D. Carter (BitsBeTrippin). Built with Claude AI assistance.
 * Licensed under the Apache License 2.0 — see LICENSE and NOTICE in the repository root.
 *
 * Rules (docs/ARCHITECTURE.md §7.5): binaries are spawned with ARGUMENT ARRAYS, never a shell
 * string; user-controlled values (paths) are passed as discrete arguments; output paths are
 * generated by the app. Binaries are located from PL_FFMPEG_PATH / PL_FFPROBE_PATH, then the
 * optional `ffmpeg-static` package if installed, then PATH. npm alone does not supply them
 * (docs/SETUP.md §1).
 */

import { spawn } from "node:child_process";
import { createRequire } from "node:module";
import path from "node:path";

export interface MediaProbe {
  durationS: number;
  container?: string;
  hasVideo: boolean;
  hasAudio: boolean;
  audioCodec?: string;
  videoCodec?: string;
  sizeBytes?: number;
}

export class MediaError extends Error {
  constructor(
    message: string,
    public readonly code: "ffmpeg_missing" | "unreadable" | "no_audio" | "silent" | "failed",
  ) {
    super(message);
    this.name = "MediaError";
  }
}

const require = createRequire(import.meta.url);

export interface MediaTools {
  ffmpeg: string;
  ffprobe: string;
  source: "env" | "ffmpeg-static" | "path";
}

/** Resolve binaries. Throws MediaError('ffmpeg_missing') with per-OS install hints when unavailable. */
export async function locateTools(): Promise<MediaTools> {
  if (process.env.PL_FFMPEG_PATH) {
    return { ffmpeg: process.env.PL_FFMPEG_PATH, ffprobe: process.env.PL_FFPROBE_PATH ?? siblingProbe(process.env.PL_FFMPEG_PATH), source: "env" };
  }
  try {
    const ffmpegStatic = require("ffmpeg-static") as string | null;
    if (ffmpegStatic) {
      let ffprobe = siblingProbe(ffmpegStatic);
      try {
        ffprobe = (require("ffprobe-static") as { path: string }).path;
      } catch {
        /* keep sibling guess */
      }
      return { ffmpeg: ffmpegStatic, ffprobe, source: "ffmpeg-static" };
    }
  } catch {
    /* not installed — fine */
  }
  const ok = await run("ffprobe", ["-version"]).then(() => true).catch(() => false);
  if (ok) return { ffmpeg: "ffmpeg", ffprobe: "ffprobe", source: "path" };
  throw new MediaError(
    process.platform === "win32"
      ? "ffmpeg/ffprobe were not found. Install with `winget install Gyan.FFmpeg`, reopen the terminal, and restart Prediction Ledger."
      : process.platform === "darwin"
        ? "ffmpeg/ffprobe were not found. Install with `brew install ffmpeg` and restart Prediction Ledger."
        : "ffmpeg/ffprobe were not found. Install ffmpeg with your package manager (e.g. `sudo apt install ffmpeg`) and restart.",
    "ffmpeg_missing",
  );
}

function siblingProbe(ffmpegPath: string): string {
  const dir = path.dirname(ffmpegPath);
  const base = path.basename(ffmpegPath).replace(/ffmpeg/i, "ffprobe");
  return path.join(dir, base);
}

export async function probe(tools: MediaTools, file: string): Promise<MediaProbe> {
  let out: string;
  try {
    out = (await run(tools.ffprobe, ["-v", "error", "-print_format", "json", "-show_format", "-show_streams", file])).stdout;
  } catch (err) {
    throw new MediaError(`The file could not be read as media (${(err as Error).message.split("\n")[0].slice(0, 160)}). Is it a valid MP4/MPEG file?`, "unreadable");
  }
  return parseProbe(out);
}

/** Pure: turn ffprobe JSON into MediaProbe (unit-tested). */
export function parseProbe(json: string): MediaProbe {
  const data = JSON.parse(json) as { format?: { duration?: string; format_name?: string; size?: string }; streams?: { codec_type?: string; codec_name?: string; duration?: string }[] };
  const streams = data.streams ?? [];
  const audio = streams.find((s) => s.codec_type === "audio");
  const video = streams.find((s) => s.codec_type === "video");
  const durationS = Number(data.format?.duration ?? audio?.duration ?? video?.duration ?? 0);
  if (!streams.length || !Number.isFinite(durationS) || durationS <= 0) throw new MediaError("No readable streams or duration in the file.", "unreadable");
  return {
    durationS: Math.round(durationS * 1000) / 1000,
    container: data.format?.format_name,
    hasVideo: !!video,
    hasAudio: !!audio,
    audioCodec: audio?.codec_name,
    videoCodec: video?.codec_name,
    sizeBytes: data.format?.size ? Number(data.format.size) : undefined,
  };
}

/** Extract/normalize audio to 16 kHz mono 16-bit PCM WAV (what Whisper expects). */
export async function extractWav(tools: MediaTools, input: string, output: string, signal?: AbortSignal): Promise<void> {
  try {
    await run(tools.ffmpeg, ["-hide_banner", "-loglevel", "error", "-y", "-i", input, "-vn", "-ac", "1", "-ar", "16000", "-c:a", "pcm_s16le", "-f", "wav", output], signal);
  } catch (err) {
    const msg = (err as Error).message;
    if (/does not contain any stream|Output file #0 does not contain any stream|Stream map .* matches no streams/i.test(msg)) throw new MediaError("The file has no audio track to transcribe.", "no_audio");
    throw new MediaError(`Audio extraction failed: ${msg.split("\n").filter(Boolean).pop()?.slice(0, 200)}`, "failed");
  }
}

/** Mean volume in dBFS via the volumedetect filter; -91 dB ≈ digital silence. */
export async function meanVolumeDb(tools: MediaTools, wav: string, signal?: AbortSignal): Promise<number> {
  const { stderr } = await run(tools.ffmpeg, ["-hide_banner", "-i", wav, "-af", "volumedetect", "-vn", "-f", "null", process.platform === "win32" ? "NUL" : "/dev/null"], signal);
  const m = /mean_volume:\s*(-?[\d.]+)\s*dB/.exec(stderr);
  return m ? Number(m[1]) : -91;
}

export const SILENCE_THRESHOLD_DB = -60;

/** Cut [startS, startS+durationS) from a WAV into its own file (used for resumable chunked transcription). */
export async function cutWav(tools: MediaTools, wav: string, startS: number, durationS: number, output: string, signal?: AbortSignal): Promise<void> {
  await run(tools.ffmpeg, ["-hide_banner", "-loglevel", "error", "-y", "-ss", String(startS), "-t", String(durationS), "-i", wav, "-ac", "1", "-ar", "16000", "-c:a", "pcm_s16le", "-f", "wav", output], signal);
}

// ---- chunk planning and stitching (pure, unit-tested) ----------------------------

export interface ChunkPlan {
  index: number;
  startS: number;
  endS: number;
}

/** Split a duration into chunks of `chunkS` with `overlapS` overlap; last chunk absorbs a short tail. */
export function planChunks(durationS: number, chunkS = 300, overlapS = 5): ChunkPlan[] {
  if (durationS <= 0) return [];
  const chunks: ChunkPlan[] = [];
  let start = 0;
  let index = 0;
  while (start < durationS) {
    let end = Math.min(durationS, start + chunkS);
    // Absorb a tail shorter than a quarter chunk into this one.
    if (durationS - end > 0 && durationS - end < chunkS / 4) end = durationS;
    chunks.push({ index, startS: round3(start), endS: round3(end) });
    if (end >= durationS) break;
    start = end - overlapS;
    index++;
  }
  return chunks;
}

export interface RawSegment {
  startS: number;
  endS: number;
  text: string;
}

/**
 * Offset a chunk's local segments to absolute time and drop those that fall inside the
 * overlap already covered by the previous chunk (keep a segment if its midpoint is past
 * the previous chunk's committed end).
 */
export function stitchChunk(chunk: ChunkPlan, local: RawSegment[], committedEndS: number): RawSegment[] {
  const out: RawSegment[] = [];
  for (const s of local) {
    const startS = round3(chunk.startS + s.startS);
    const endS = round3(chunk.startS + Math.max(s.endS, s.startS));
    const mid = (startS + endS) / 2;
    if (mid <= committedEndS) continue; // already covered by previous chunk's overlap
    const text = s.text.trim();
    if (!text) continue;
    out.push({ startS: Math.max(startS, committedEndS), endS, text });
  }
  return out;
}

const round3 = (n: number) => Math.round(n * 1000) / 1000;

// ---- process helper ----------------------------------------------------------------

export function run(cmd: string, args: string[], signal?: AbortSignal): Promise<{ stdout: string; stderr: string }> {
  return new Promise((resolve, reject) => {
    const child = spawn(cmd, args, { windowsHide: true, stdio: ["ignore", "pipe", "pipe"] });
    let stdout = "";
    let stderr = "";
    child.stdout.on("data", (d) => (stdout += d.toString()));
    child.stderr.on("data", (d) => (stderr += d.toString().slice(0, 8000)));
    const onAbort = () => child.kill("SIGTERM");
    signal?.addEventListener("abort", onAbort, { once: true });
    child.on("error", (err) => {
      signal?.removeEventListener("abort", onAbort);
      reject(new Error(`${cmd}: ${err.message}`));
    });
    child.on("close", (code) => {
      signal?.removeEventListener("abort", onAbort);
      if (code === 0) resolve({ stdout, stderr });
      else reject(new Error(stderr.trim() || `${cmd} exited with code ${code}`));
    });
  });
}
